/*
 * @author: yuting.zhou
 * @description: Default config of this module
 * Generated by model2view cli
 */
export const defaultEntity = {
  {{#pairs}}
  {{variable}}: '',
  {{/pairs}}
};

export const defaultSearchConditions = {
  {{#pairs}}
  {{variable}}: '',
  {{/pairs}}
};

export const baseColumns = [
  {{#pairs}}
  {
    title: \'{{label}}\',
    key: '{{variable}}',
  },
  {{/pairs}}
];
