/*
 * @author: yuting.zhou
 * @description: Default config of this module
 * Generated by daneel cli
 */

export const defaultEntity = {
  {{#pairs}}
  {{variable}}: '',
  {{/pairs}}
};

export const defaultSearch = {
  {{#pairs}}
  {{variable}}: '',
  {{/pairs}}
  page: {
    pageNo: 1,
    pageSize: 20,
  },
};

export const baseColumns = [
  {
    type: 'selection',
    width: 60,
    align: 'center',
  },
  {{#pairs}}
  {
    title: '{{label}}',
    key: '{{variable}}',
  },
  {{/pairs}}
];

export const MODE = {
  VIEW: 'VIEW',
  ADD: 'ADD',
  EDIT: 'EDIT',
};
